DROP TABLE IF EXISTS viaje CASCADE;
DROP TABLE IF EXISTS recarga CASCADE;
DROP TABLE IF EXISTS tarifa CASCADE;
DROP TABLE IF EXISTS tarjeta CASCADE;
DROP TABLE IF EXISTS paraderoruta CASCADE;
DROP TABLE IF EXISTS ruta CASCADE;
DROP TABLE IF EXISTS paradero CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;
