name: Continuous Deployment
on:
  push:
    branches:
      - master

jobs:
  delivery:
    uses: ./.github/workflows/cd.yml
    secrets: inherit

  deploy:
    needs: delivery
    uses: ./.github/workflows/deploy.yml
    secrets: inherit