name: Continuous Deployment
on:
  push:
    branches:
      - master
permissions:
  contents: read
  packages: write
jobs:
  delivery:
    uses: ./.github/workflows/delivery.yml
    secrets: inherit

  deploy:
    needs: delivery
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
