name: Commit Stage

on:
  workflow_call:

jobs:
  commit-stage:
    name: Unit Tests
    runs-on: ubuntu-latest
    container: maven:3.9-eclipse-temurin-21-alpine

    steps:
      - uses: actions/checkout@v4

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Unit Tests
        run: mvn test