name: Continuous Delivery

on:
  push:
    branches:
      - release
  workflow_call:

jobs:
  perform-tests-and-integration:
    uses: ./.github/workflows/integration.yml
    secrets: inherit

  build-artifact:
    name: Build Application Artifact
    needs: perform-tests-and-integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: elimapass-spring-app
          path: target/*.jar
          retention-days: 14

  performance-tests:
    needs: [perform-tests-and-integration, build-artifact]
    uses: ./.github/workflows/performance.yml
    secrets: inherit