name: Continuous Delivery

on:
  push:
    branches:
      - release
  workflow_call:

jobs:
  perform-tests-and-integration:
    uses: ./.github/workflows/integration.yml
    secrets: inherit

  build-artifact:
    name: Build Application Artifact
    needs: perform-tests-and-integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: elimapass-spring-app
          path: target/*.jar
          retention-days: 14

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/elimapass-spring:latest .

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/elimapass-spring:latest

  functional-tests:
    runs-on: ubuntu-latest
    needs: build-artifact
    steps:
    - name: Trigger frontend functional tests
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        repository: fcuya13/eLimaPass
        event-type: backend-updated

  performance-tests:
    needs: [perform-tests-and-integration, build-artifact, functional-tests]
    uses: ./.github/workflows/performance.yml
    secrets: inherit