name: integration.yml
on:
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports: [ 5432:5432 ]
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: elimapass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    container:
      image: maven:3.9-eclipse-temurin-21-alpine

    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/elimapass
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: testpass
      SPRING_JPA_HIBERNATE_DEFAULT_SCHEMA: elimapass

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        run: apk add --no-cache nodejs npm

      - name: Install newman
        run: npm install -g newman y npm install -g newman-reporter-html

      - name: Build Spring Boot App
        run: mvn clean package -DskipTests

      - name: Run Spring Boot and Jmeter Test
        run: |
          java -jar target/*.jar \
            --spring.datasource.url=jdbc:postgresql://postgres:5432/elimapass \
            --spring.datasource.username=testuser \
            --spring.datasource.password=testpass &
          export SPRING_PID=$!
          
          echo "Sleeping 15 seconds before running Tests..."
          sleep 15
          
          newman run tests/eLimaPass-Spring.postman_collection.json -r cli,html --reporter-html-export reports/report.html

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: reports/