name: JMeter Performance Test

on: [push, pull_request]

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports: [5432:5432]
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: elimapass
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    container:
      image: maven:3.9-eclipse-temurin-21-alpine

    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/elimapass
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: testpass
      SPRING_JPA_HIBERNATE_DEFAULT_SCHEMA: elimapass

    steps:
      - uses: actions/checkout@v4

      - name: Wait for Postgres to be ready
        run: |
          for i in {1..30}; do
            pg_isready -h postgres -U testuser && break
            sleep 2
          done

      - name: Build Spring Boot App
        run: mvn clean package -DskipTests

      - name: Run Spring Boot app in background
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: jmeter/test.jmx
          outputReportsFolder: reports/
        run: |
          apk add --no-cache openjdk17-jre wget unzip

          JMETER_VERSION=5.6.3
          wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-${JMETER_VERSION}.zip
          unzip apache-jmeter-${JMETER_VERSION}.zip

          java -jar target/*.jar \
            --spring.datasource.url=jdbc:postgresql://postgres:5432/elimapass \
            --spring.datasource.username=testuser \
            --spring.datasource.password=testpass &

          for i in {1..30}; do
            if wget -qO- http://localhost:8080/elimapass/v1/actuator/health | grep UP; then
              echo "Backend is UP"
              break
            fi
            sleep 2
          done

          ./apache-jmeter-${JMETER_VERSION}/bin/jmeter -n -t jmeter/test.jmx -l jmeter_log.log -e -f -o reports/ 


