name: JMeter Performance Test

on: [push, pull_request]

jobs:
  jmeter-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports: [5432:5432]
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    container:
      image: maven:3.9-eclipse-temurin-21-alpine

    steps:
      - uses: actions/checkout@v4

      - name: Wait for Postgres to be ready
        run: |
          for i in {1..30}; do
            pg_isready -h postgres -U testuser && break
            sleep 2
          done

      - name: Build Spring Boot App
        run: mvn clean package -DskipTests

      - name: Run Spring Boot app in background
        run: |
          java -jar target/*.jar \
            --spring.datasource.url=jdbc:postgresql://postgres:5432/testdb \
            --spring.datasource.username=testuser \
            --spring.datasource.password=testpass &
          sleep 15

      - name: Wait until Spring Boot is UP
        run: |
          for i in {1..30}; do
            if wget -qO- http://localhost:8080/actuator/health | grep UP; then
              echo "Backend is UP"
              exit 0
            fi
            sleep 2
          done
          echo "Spring Boot not available"
          exit 1

      - name: Install JMeter
        run: |
          apk add --no-cache jmeter

      - name: Run JMeter performance tests
        run: |
          jmeter -n -t jmeter/mi_escenario.jmx -l resultados.jtl