name: Java CI with Maven

on:
  push:
    branches:
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: maven:3.9-eclipse-temurin-21-alpine

    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: elimapass-password
          POSTGRES_DB: elimapass
        ports:
          - 5432:5432  # Using standard PostgreSQL port
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Configure PostgreSQL connection
        run: |
          echo "spring.datasource.url=jdbc:postgresql://postgres:5432/elimapass" > src/main/resources/application-ci.properties
          echo "spring.datasource.username=postgres" >> src/main/resources/application-ci.properties
          echo "spring.datasource.password=elimapass-password" >> src/main/resources/application-ci.properties

      - name: Perform tests
        run: mvn test -Dspring.profiles.active=ci

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=fcuya13_eLimaPass-spring -Dspring.profiles.active=ci



